### ISSUE TITLE
Error in the staggered adoption code

### ISSUE THREAD

**Issue by Germancampos** [ebenmichael/augsynth#69]
Hello everyone,

I am developing an impact evaluation research and I was interested in the staggered adoption methodology developed by you. At the moment, I'm trying to replicate the code in the "augsynth: Estimating treatment effects with staggered adoption" section, and I'm getting the same error Arturo mentioned last month.

The code I run is the following:

# with a choice of nu
ppool_syn <- multisynth(lnppexpend ~ cbr, State, year,
                         nu = 0.5, analysis_df)

The mistake is:
Error in `mutate()`:
! Problem while computing `trt_time = replace_na(trt_time, Inf)`.
Caused by error in `stop_vctrs()`:
! Can't convert from `replace` <double> to `data` <integer> due to loss of precision.
*Locations: 1

Could you please tell me how to solve this problem?

Thank you very much, greetings.

**Comment by idg23** [comment]
Same for me

**Comment by ebenmichael** [comment]
This is fixed now per #68

**Comment by idg23** [comment]
Hey, apologies for circling back to this. I still get the same error as described above. I tried re-installing the package but the error still persists. Any suggestions as to how to handle this?
